services:
  backend:
    build: ./backend
    #platform: linux/amd64
    ports:
      - '4000:4000'
    networks:
      - app-network

  frontend:
    build: ./frontend
    platform: linux/amd64

    ports:
      - '3000:80'
    depends_on:
      - backend
    networks:
      - app-network

  

networks:
  app-network:
    driver: bridge